### ISSUE TITLE
Error in create-magento-app

### ISSUE THREAD

**Issue by nikilmethew** [scandipwa/create-magento-app#106]
### Describe the bug

Install scandipwa magento 2 using create-magento-app. It throws error on "Installing Magento 2.4.4" step.

### Which terms did you search for in User Guide?

We follow the below link to install the pwa site
(https://docs.create-magento-app.com/getting-started/getting-started)

### Environment

Ubuntu 18.04.6

### Steps to reproduce

(Write your steps here:)

1. Install in local server
2. create-scandipwa-app is working fine. 
3. create-magento-app throws error.

### Expected behavior

How to complete the installation for the create-magento-app and integrate the scandipwa-app with magento 2.

### Actual behavior

https://tinyurl.com/282c7vbn

**Comment by ejnshtein** [comment]
Well, you can upload images to GitHub too.

As for the error, I suspect that you run `magento-scripts` or composer in your system as root at some point and it broke permissions in your user home directory.
Try running `sudo chmod -R 777 ~/.composer`
