### ISSUE TITLE
No git in PHP container

### ISSUE THREAD

**Issue by arko-betersport** [scandipwa/create-magento-app#109]
### Describe the bug

`composer install` failed with the error: git was not found in your PATH, skipping source download

### Environment

magento-scripts version: 2.0.0-alpha.10 

### Steps to reproduce

1. Run `composer install` when you have some modules that only can be installed via SSH.

### Expected behavior
No error.

### Actual behavior

Error: git was not found in your PATH, skipping source download
After I ran `apk add git` in the PHP container, there error was gone.

**Comment by ejnshtein** [comment]
All PHP images are updated, you will need to pull a new image version and you will be good to go!

**Comment by ejnshtein** [comment]
If you update to [2.0.0-alpha.12](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%402.0.0-alpha.12) you will be able to run `npm start -- --pull-images` to pull newest PHP image!
