### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by matteobaro** [scandipwa/create-magento-app#12]
Hello,
i'm trying to install create-magento-app multiple time but always i'm not able to see the magento installation

always nginx 404 Not Found

all docker are up

yarn status ok

any suggestion ?

thanks

**Comment by ejnshtein** [comment]
Hi!
Can you provide some logs, screenshots and version that you are running?

**Comment by ejnshtein** [comment]
Closing issue since no details had been provided.

**Comment by v3ss0n** [comment]
This is the same problem i am facing.

**Comment by ejnshtein** [comment]
are you on windows?\
