### ISSUE TITLE
docker: Error response from daemon: failed to mount local volume: mount /home/misael/scandi/my-app/node_modules/.create-magento-app-cache/nginx/conf.d:/var/lib/docker/volumes/my-app_nginx-data/_data, flags: 0x1000: no such file or directory.

### ISSUE THREAD

**Issue by redati** [scandipwa/create-magento-app#13]
WSL2 Windows 10 Ubuntu

is a bug or lack of some dependency

root@decora1:/home/misael/scandi/my-app# yarn start
yarn run v1.22.5
$ magento-scripts start
❯ Starting project
  ↓ Cache folder already created! [SKIPPED]
  ✔ Checking requirements
    ✔ Running on linux 5.4.72-microsoft-standard-WSL2
    ✔ Using PHPBrew version 1.27.0
    ✔ Using docker version 20.10.2
    ✔ Checking composer
  ✔ Using Magento 2.4.1
  ✔ Get cached ports
  ✔ Stopping Docker services
    ✔ Stopping containers
  ↓ Stopping php-fpm [SKIPPED]
  ✔ Get available ports
  ✔ Saving configuration
  ✔ Using PHP version 7.4.13, checking extensions...
    ↓ Configuring PHP extensions [SKIPPED]
  ✔ Install Composer, prepare FS & download images
    ✔ Using composer version 1.10.20
    ✔ Preparing file system
      ✔ Setting nginx config
      ✔ Setting php-fpm config
      ✔ Setting PHP config
    ↓ Pulling container images [SKIPPED]
  ↓ Installing Prestissimo [SKIPPED]
  ✔ Magento installed!
  ❯ Starting docker services
    ✔ Prepare services
      ↓ Deploying docker network [SKIPPED]
      ↓ Creating volumes [SKIPPED]
      ↓ Pulling container images [SKIPPED]
    ✖ Starting containers
  ◼ Setup magento
  ◼ Starting php-fpm
  ◼ Open browser
ERROR! docker: Error response from daemon: failed to mount local volume: mount /home/misael/scandi/my-app/node_modules/.create-magento-app-cache/nginx/conf.d:/var/lib/docker/volumes/my-app_nginx-data/_data, flags: 0x1000: no such file or directory.
See 'docker run --help'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ejnshtein** [comment]
Hi!
Can you run command `docker volume inspect my-app_nginx-data` and provide its output?

**Comment by redati** [comment]
"@scandipwa/magento-scripts": "1.2.0"
docker volume inspect my-app_nginx-data
[
    {
        "CreatedAt": "2021-02-18T23:59:55Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/my-app_nginx-data/_data",
        "Name": "my-app_nginx-data",
        "Options": {
            "device": "/home/misael/decora/scandi/my-app/node_modules/.create-magento-app-cache/nginx/conf.d",
            "o": "bind",
            "type": "nfs"
        },
        "Scope": "local"
    }
]

**Comment by ejnshtein** [comment]
As you can see, path that is used to mount nginx volume is different from directory that your are actually located in.
This can be fixed in 2 ways:
1. Delete all old `my-app_*` volumes.
2. Wait for the upcoming release where will be introduced prefixes that will allow usage of same folder names across the system.

**Comment by redati** [comment]
Thanks

I tried it on another computer, then it gave the same error, but this is the computer that gave the first error.

[
    {
        "CreatedAt": "2021-02-18T18:24:08Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/my-app_nginx-data/_data",
        "Name": "my-app_nginx-data",
        "Options": {
            "device": "/home/misael/scandi/my-app/node_modules/.create-magento-app-cache/nginx/conf.d",
            "o": "bind",
            "type": "nfs"
        },
        "Scope": "local"
    }
]

**Comment by ejnshtein** [comment]
How many `my-app` folders do you have?

**Comment by ejnshtein** [comment]
Okay, then you will have to wait for the upcoming release. It will be out today.

**Comment by ejnshtein** [comment]
Okay, you can update to version 1.2.1, it should resolve issues with folder names.
