### ISSUE TITLE
Hardcoded search-engine parameter in magento installation step fails on Magento 2.4.7-beta2

### ISSUE THREAD

**Issue by ejnshtein** [scandipwa/create-magento-app#139]
### Describe the bug

Due to hardcoded `elasticsearch7` as a search-engine parameter during Magento installation, it fails because Magento 2 uses incorrect search engine driver (as I understood). Setting search-engine parameter to `elasticsearch8` fixes the problem, but I also think this needs to be addressed as in the scope of [OpenSearch integration to CMA](https://github.com/scandipwa/create-magento-app/issues/128).

https://github.com/scandipwa/create-magento-app/blob/master/build-packages/magento-scripts/lib/tasks/magento/setup-magento/install-magento.js#L112

### Additional Info

It worked on my Fedora 39 system, but on a WSL2-based system with Ubuntu 22.04, it failed. Good thing I discovered this, bad thing that it even happened.

**Comment by ejnshtein** [comment]
Also affects Magento 2.4.6

**Comment by Andrii-Antoniuk** [comment]
Yes.
I think this also was addressed internally and marked as "don't use WSL to not have problems" 😅

**Comment by ejnshtein** [comment]
Yeah, well, at my current system, I can't run native Linux unfortunately, because of [awesome AMD video drivers in Linux kernel](https://community.frame.work/t/tracking-graphical-corruption-in-fedora-39-amd-3-03-bios/39073/169?page=8).
So back to Windows 11, where Windows Hello works, sleep works, all games work, no weird Bluetooth connection issues... Only negatives, as you can see, and discovering bugs from day 1 of installing this stuff.

**Comment by ejnshtein** [comment]
Will be fixed in v2.3.0
