### ISSUE TITLE
Missing system dependency (libxml2)

### ISSUE THREAD

**Issue by joostm020** [scandipwa/create-magento-app#14]
### Describe the bug

When performing a clean install using create-magento-app after having installed all the required system dependencies according to the documentation, the system dependency "libxml2" is missing.

### Did you try recovering your dependencies?

N.a.

### Which terms did you search for in User Guide?

Documentation for prerequisites:
https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-macos
libxml2

### Environment

Macbook Pro Big Sur 11.2.1

### Steps to reproduce

1. Follow the documentation for create-magento-app on a clean system where libxml2 is not yet installed

### Expected behavior

Not run into missing dependencies.

### Actual behavior

Error compiling due to missing dependency.

### Error details:
    ✖ Failed to compile the required PHP version.
      Tried compiling the PHP version 7.4.13.
      Use your favorite search engine to resolve the issue.
      Most probably you are missing some dependencies.
      See error details in the output below.
      ===> phpbrew will now build 7.4.13
      ===> Loading and resolving variants...
      Homebrew prefix "/usr/local/Cellar/libxml2/2.9.10_2" does not exist.

**Comment by ejnshtein** [comment]
Thanks for the report.
Will update docs soon!

**Comment by ejnshtein** [comment]
Docs updated!
https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-macos

**Comment by joostm020** [comment]
Thanks.
