### ISSUE TITLE
ERROR! Code: 1 - Response: SQLSTATE[HY000] [2006] MySQL server has gone away

### ISSUE THREAD

**Issue by joostm020** [scandipwa/create-magento-app#15]
### Describe the bug

When starting a new Magento 2 (create-magento-app) Application you'll get an MySQL error on the initial run:
SQLSTATE[HY000] [2006] MySQL server has gone away

### Did you try recovering your dependencies?

N.a.

### Which terms did you search for in User Guide?

Only the current known workaround is provided:
https://docs.create-magento-app.com/troubleshooting/common-issues#sqlstate-hy-000-2006-mysql-server-has-gone-away

### Environment

Macbook Pro Big Sur 11.2.1

### Steps to reproduce

1. Run "create-magento-app my-magento"
2. Run "yarn start"
3. Wait for the stack to do it's things (this might take a little while).
3. Eventually you'll run into the SQL error (initial run only)

### Expected behavior

No MySQL error.

### Actual behavior

MySQL error:
SQLSTATE[HY000] [2006] MySQL server has gone away

### Workaround

Running "yarn start" again for the second time seems to fix the issue, but of course this is only a workaround.

**Comment by ejnshtein** [comment]
Here's solution https://docs.create-magento-app.com/troubleshooting/common-issues#sqlstate-hy-000-2006-mysql-server-has-gone-away

**Comment by joostm020** [comment]
> Here's a solution https://docs.create-magento-app.com/troubleshooting/common-issues#sqlstate-hy-000-2006-mysql-server-has-gone-away

Weird that the search results didn't return anything when I searched for "MySQL" and "SQL", I tried again after a cache reset and did indeed see this same article.

Anyways it does only provide a workaround but not fix the actual issue.

**Comment by ejnshtein** [comment]
True, I haven't found a "true" solution since idk why this issue appears in the first place. Also, it happens randomly on some systems 
or does not appear at all 🤔

**Comment by ejnshtein** [comment]
Okay, found a solution on [docker hub MySQL readme](https://hub.docker.com/_/mysql). Down below there's a **No connections until MySQL init completes** section that describes this issue with container first start with empty DB.
So, I connected to MySQL directly from `magento-scripts` and inside while loop just waiting for successful connection. On my Macbook Pro with i7-7820HQ, it took about 20-25 seconds to successfully connect to MySQL. https://github.com/scandipwa/create-magento-app/blob/4eefaad60620349a2e7fe61066b924d5116b0604/build-packages/magento-scripts/lib/tasks/mysql/connect-to-mysql.js#L12-L31

**Comment by ejnshtein** [comment]
This is currently released in [v1.2.3-alpha.0](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.2.3-alpha.0) which should become stable v1.2.3 later this week.
