### ISSUE TITLE
The site is not displayed in the browser

### ISSUE THREAD

**Issue by wmycco1** [scandipwa/create-magento-app#156]
The site is not displayed in the browser Magento ver. 2.4.7-p1 + ScandiPWA ver. 6.4.0

Ubuntu version: 22.04
Nginx version: 1.24.0
Mysql Ver 8.0.38
Redis server v=7.2.5
PHP 8.2.21
Node v20.16.0
Opensearch=2.5.0
Yarn --version 1.22.22

1. Magento ver. 2.4.7-p1 installed
2. ScandiPWA ver. installed. 6.4.0 as a theme

As an observation
### Steps to reproduce
1. Open the browser Inspector
2. Refresh the site page in your browser several times and you will see that the content on the page will disappear
3. Switch to the Console tab and you will see the message:
react-dom.production.min.js:322 Uncaught (in promise) Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n.render (react-dom.production.min.js:322:69)
    at 86558 (render.tsx:48:1)
    at Function.n ((индекс):105:112568)

I expect pages to reload correctly with browser cache enabled and therefore display website content correctly

Additional resources

/var/www/my-app.com/src/localmodules/my-app/package.json:
{
    "name": "my-app",
    "version": "0.0.1",
    "license": "OSL-3.0",
    "dependencies": {
        "@scandipwa/scandipwa": "6.4.0",
        "@scandipwa/scandipwa-scripts": "2.5.0",
        "@scandipwa/eslint-config": "0.2.2",
        "@scandipwa/ts-server-plugin": "0.0.5",
        "@tilework/mosaic": "1.0.1",
        "@tilework/mosaic-craco": "1.0.1",
        "@types/react": "18.2.74",
        "@types/node": "20.12.4",
        "postcss": "8.4.5",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "react-redux": "8.0.2",
        "@babel/plugin-transform-typescript": "7.20.2"
    },
    "devDependencies": {
        "@babel/plugin-proposal-private-property-in-object": "7.21.11",
        "@babel/plugin-transform-private-property-in-object": "7.24.1"
    },
    "scandipwa": {
        "type": "theme",
        "locales": {
            "en_US": true
        },
        "parentTheme": "@scandipwa/scandipwa",
        "extensions": {
            "@scandipwa/ts-server-plugin": true
        }
    },
    "scripts": {
        "start": "scandipwa-scripts start",
        "build": "scandipwa-scripts build"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "proxy": "https://40kskudemo.scandipwa.com/"
}

/var/www/my-app.com/src/localmodules/my-app/composer.json:
{
    "name": "scandipwa/my-app",
    "description": "N/A",
    "version": "0.0.1",
    "type": "magento2-theme",
    "license": [
        "proprietary"
    ],
    "require": {
        "magento/framework": "*",
        "scandipwa/service-worker": "1.0.3",
        "scandipwa/installer": "4.0.1",
        "scandipwa/persisted-query": "3.1.1",
        "scandipwa/slider-graphql": "2.1.1",
        "scandipwa/cms-graphql": "1.4.7",
        "scandipwa/catalog-graphql": "3.4.0",
        "scandipwa/route717": "2.1.6",
        "scandipwa/performance": "1.5.7",
        "scandipwa/customer-graph-ql": "4.1.0",
        "scandipwa/quote-graphql": "3.1.0",
        "scandipwa/wishlist-graphql": "2.0.17",
        "scandipwa/urlrewrite-graphql": "1.3.9",
        "scandipwa/store-graphql": "1.3.1",
        "scandipwa/customization": "2.0.4",
        "scandipwa/cache": "1.1.5",
        "scandipwa/locale": "2",
        "scandipwa/contact-graphql": "1.0.0",
        "scandipwa/compare-graphql": "1.0.9",
        "scandipwa/customer-downloadable-graphql": "1.0.5",
        "scandipwa/directory-graphql": "1.0.2",
        "scandipwa/product-alerts-graphql": "1.0.1",
        "scandipwa/sales-graphql": "1.3.2",
        "scandipwa/catalog-customer-graphql": "1.0.1",
        "scandipwa/review-graphql": "1.0.0"
    },
    "autoload": {
        "files": [
            "magento/registration.php"
        ]
    }
}

**Comment by ejnshtein** [comment]
The error you described is from the scandipwa, not the Magento application.

I think you should open an issue in the [scandipwa repo](https://github.com/scandipwa/scandipwa) then. But the project is mostly on life support, so it is not guaranteed that you will get an answer for your issue.

I recommend you share screenshots/make a video recording of your problem, it is hard to understand otherwise how it looks for you.

Closing the issue. 🙂
