### ISSUE TITLE
ERROR! Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by arko-betersport** [scandipwa/create-magento-app#16]
### Describe the bug

After a reboot of my MacBook (using restart with "Reopen windows when logging back in."), I ran `yarn start` to restart my Magento installation but it crashed with the error: `ERROR! Cannot read property 'includes' of undefined`

### Did you try recovering your dependencies?

I ran `yarn start` again to see if it was a one time issue, but it was not. I also ran a `yarn upgrade` but everything was already up-to-date.

### Environment

OS: macOS Big Sur (11.2.1)
magento-scripts: 1.2.2-alpha.0 (latest version)

### Steps to reproduce

(Write your steps here:)

1. Reboot MacBook ("Reopen windows when logging back in." enabled) while Magento is running in background
2. Run `yarn start`

### Expected behavior

Start my Magento installation again.

### Actual behavior

Start resulted in an error.
![image](https://user-images.githubusercontent.com/78349099/109292086-220a6c00-782a-11eb-9216-252d0ab66c84.png)

**Comment by ejnshtein** [comment]
Thanks for the report!
This issue will be fixed in the upcoming update v1.2.2!

**Comment by ejnshtein** [comment]
Closing an issue since the problem was resolved.
