### ISSUE TITLE
Can't install Magento app MacOs - BigSur

### ISSUE THREAD

**Issue by websuits** [scandipwa/create-magento-app#18]
### Describe the bug

All steps were followed but something is wrong with the sqlite3. When i run npm start on compiling php step, returns an error. pasting logs below.

Note that i've installed via brew sqlite3 and every other tool available for it. Updated xCode.

### Which terms did you search for in User Guide?

sqlite3 magento app php

### Environment

MacOs - Big Sur 11.2.2

### Steps to reproduce

All steps from https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-macos

### Expected behavior

Install behave normally without errors.

### Actual behavior

Configuring extensions
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking for strtoll... yes
checking for atoll... yes
checking whether to build with LIBXML support... yes
checking for libxml-2.0 >= 2.7.6... yes
checking for OpenSSL support... yes
checking for Kerberos support... no
checking whether to use system default cipher list instead of hardcoded value... no
checking for RAND_egd... no
checking for openssl >= 1.0.1... yes
checking for PCRE library to use... bundled
checking whether to enable PCRE JIT functionality... yes
checking whether Intel CET is enabled... no
checking whether to enable the SQLite3 extension... yes
checking for sqlite3 > 3.7.4... no
configure: error: Package requirements (sqlite3 > 3.7.4) were not met:

No package 'sqlite3' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SQLITE_CFLAGS
and SQLITE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by websuits** [comment]
First issue solved following tutorial : 
https://tableplus.com/blog/2018/08/download-install-sqlite-for-mac-osx-in-5-minutes.html


New issue :


checking for libxslt >= 1.1.0... no
configure: error: Package requirements (libxslt >= 1.1.0) were not met:

No package 'libxslt' found

**Comment by ejnshtein** [comment]
Can't tell for sure, I'm running on bigsur 11.1 and no such problem.
Probably these dependencies are just missing from your system.

Also, what's interesting, I'm running bigsur 11.1 and my CMA says that I'm running on macOS 10.16.0, while you are running bigsur 11.2.2 and it's macOS 11.0.0. Hmmmmm...

**Comment by websuits** [comment]
> Can't tell for sure, I'm running on bigsur 11.1 and no such problem.
> Probably these dependencies are just missing from your system.
> 
> Also, what's interesting, I'm running bigsur 11.1 and my CMA says that I'm running on macOS 10.16.0, while you are running bigsur 11.2.2 and it's macOS 11.0.0. Hmmmmm...

The thing is that for the last log there is no actual error it just fails.

**Comment by ejnshtein** [comment]
Try running the command `phpbrew clean`. It should clean up build directory. Then run start again.

**Comment by websuits** [comment]
I installed zlib manually from https://zlib.net/ and passed this step, will see if everything will work now.

**Comment by ejnshtein** [comment]
The only docs that we have online are https://docs.create-scandipwa-app.com/ and https://docs.scandipwa.com/

**Comment by websuits** [comment]
Thanks.

Unfortunately the problems don't end here.

Code: 1
        Response: SQLSTATE[HY000] [2006] MySQL server has gone away

In InstallCommand.php line 274:

  Parameter validation failed

https://prnt.sc/10d293l

**Comment by ejnshtein** [comment]
This one is expected

Just run start command again

**Comment by ejnshtein** [comment]
Dunno, why this error appears in the first place. Will be investigating and fixing it in the next patch release.

**Comment by websuits** [comment]
Finally, i can actually use it. Thanks for your feedback!

**Comment by ejnshtein** [comment]
Good luck)
