### ISSUE TITLE
 ERROR! Cannot read property "value" of undefined

### ISSUE THREAD

**Issue by shivampmc** [scandipwa/create-magento-app#19]
![image](https://user-images.githubusercontent.com/77787433/110439341-58bf6c80-80dd-11eb-9dea-7014878bd00c.png)

I'm running the latest create-magento-app script cloned just now to my local system.
I am running it on Linux Mint 20.

This is the error I am getting when I am running yarn start, could not find any solution for this. Any help would be highly appreciated. Thanks in advance.

**Comment by arko-betersport** [comment]
I got the same issue, downgrading to version 1.2.2 worked for me.

**Comment by shivampmc** [comment]
> 
> 
> I got the same issue, downgrading to version 1.2.2 worked for me.

Thank you for answering :), would you mind pointing me to some article or blog which shows how to downgrade?

**Comment by shivampmc** [comment]
> 
> 
> I got the same issue, downgrading to version 1.2.2 worked for me.

Thank you so much for answering, will try that now.

**Comment by ejnshtein** [comment]
I think it's also time to move to typescript 🤔
Too many type-errors lately, even on alpha version where that is kinda expected, but still.

**Comment by shivampmc** [comment]
> 
> 
> I think it's also time to move to typescript 🤔
> Too many type-errors lately, even on alpha version where that is kinda expected, but still.

Rewriting it would be a nightmare, no? 🤯

**Comment by ejnshtein** [comment]
No, I rewrote my personal projects to typescript already, shouldn't be a problem.

**Comment by shivampmc** [comment]
> 
> 
> No, I rewrote my personal projects to typescript already, shouldn't be a problem.

Oh, that's sounds great.

**Comment by ejnshtein** [comment]
BTW, I fixed the type error for the alpha version in [v1.2.3-alpha.1](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.2.3-alpha.1).
You can either update to it or use a stable version of scripts which is currently [v1.2.2](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.2.2).

**Comment by shivampmc** [comment]
> 
> 
> BTW, I fixed the type error for the alpha version in [v1.2.3-alpha.1](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.2.3-alpha.1).
> You can either update to it or use a stable version of scripts which is currently [v1.2.2](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.2.2).

Thank you for the quick fix ☺, but looks like I will stick with the stable build for quite a while.

**Comment by ejnshtein** [comment]
You can safely update to [v1.3.1](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.3.1) 🙌

**Comment by shivampmc** [comment]
Thank you :)
Will try it later today or maybe tomorrow.

**Comment by ejnshtein** [comment]
Hey!
How's your "tomorrow" went?

**Comment by shivampmc** [comment]
Oh, I forgot to leave a message in here. Actually, when I am trying to create a new app using yarn create magento-app app_name, I am getting V1.2.1.

**Comment by ejnshtein** [comment]
`yarn create magento-app@latest app_name` ?

Well, you can just update it manually
