### ISSUE TITLE
ERROR! Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by arko-betersport** [scandipwa/create-magento-app#20]
### Describe the bug

`yarn import-db` results in an error.  
The database however is imported and after running `yarn start` everything looks good.

### Environment

OS: macOS Big Sur (11.2.1)
magento-scripts: 1.3.0 (latest version)

### Steps to reproduce

1. Import db using `yarn import-db`

### Expected behavior

Database would be imported and no errors.

### Actual behavior

![image](https://user-images.githubusercontent.com/78349099/111307174-5dde6780-8659-11eb-9f3d-cdeae5f38127.png)

**Comment by ejnshtein** [comment]
Oh, that's unfortunate.
Try running the start command with the --import-db option then.

Gonna fix it in v1.3.1.

**Comment by arko-betersport** [comment]
Have not tried `yarn start --import-db` before, but that one works fine

**Comment by ejnshtein** [comment]
Fixed in [v1.3.1](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.3.1)

**Comment by arko-betersport** [comment]
I tried to test the new version, but there is another error.  
![image](https://user-images.githubusercontent.com/78349099/111497531-775ade80-8741-11eb-8c69-17f547b7897c.png)

I tried to import a backup that I created a few minutes earlier using: `m s:b --db`

**Comment by ejnshtein** [comment]
Is database empty?

**Comment by arko-betersport** [comment]
Both the backup file and the database are filled and the core_config_data table exists.  
But the `design/theme/theme_id` path the program looks for doesn't exist.

**Comment by ejnshtein** [comment]
It should exist since this is a part of Magento theme configuration.
Try emptying database and reinstall magento.
To do that:
1. stop CMA.
2. delete MySQL docker volume
3. delete `app/etc/env.php` file
4. run `start`

**Comment by arko-betersport** [comment]
Same result. `start` has similar issues when importing the db. I looked at the configuration in the Magento interface and I am using the default theme settings.
![image](https://user-images.githubusercontent.com/78349099/111958634-bf855280-8aed-11eb-8b91-7571a3783ca1.png)

**Comment by ejnshtein** [comment]
Okay, just checked and can say that problem is legit.
  When Magento 2 is just installed and no theme configuration is set theme's no such entry in the `core_config_data` table.
  A fix is ready and will be released in v1.3.2.

**Comment by ejnshtein** [comment]
Done, try [v1.3.2](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.3.2)!

**Comment by arko-betersport** [comment]
I can confirm that `import-db` is working now! Thank you!
