### ISSUE TITLE
"Explore Application Logs" Documentation Fix 

### ISSUE THREAD

**Issue by jbruni** [scandipwa/create-magento-app#21]
### Describe the bug

Documentation page: https://docs.create-magento-app.com/getting-started/available-commands/logs

![doc-issue](https://user-images.githubusercontent.com/69181/113014804-ea555380-914a-11eb-96ab-f3326c46049e.png)

The correct commands are `yarn logs <scope>` or `npm run logs -- <scope>` 

### Did you try recovering your dependencies?

N/A

### Which terms did you search for in User Guide?

N/A

### Environment

N/A

### Steps to reproduce

N/A

### Expected behavior

I expected to find a documentation repository, and submit a Pull Request...

### Actual behavior

...found some archived documentation repositories.

**Comment by ejnshtein** [comment]
Thanks!!!

Fixed!
