### ISSUE TITLE
Tail container logs

### ISSUE THREAD

**Issue by arko-betersport** [scandipwa/create-magento-app#22]
### Is your proposal related to a problem?

When checking for example the nginx logs using `yarn logs nginx` the whole log is returned, which may take a while.

### Describe the solution you'd like

When you check the nginx container logs using the `docker logs` command you can choose to only show the last n log entries using the tail flag: `docker logs <container> --tail 50`  
   
Maybe the tail flag can be forwarded to docker when using the `yarn logs` command.

**Comment by ejnshtein** [comment]
Ohh true, this will be great!

**Comment by ejnshtein** [comment]
Also, we have 2 templates for issues: bug and proposal, this one sure is a proposal but u made it like a bug :D

**Comment by arko-betersport** [comment]
Completely missed the proposal template, sorry. I updated the issue with the correct template.

**Comment by ejnshtein** [comment]
I've added options to `logs` command that mimic `docker logs` command options in [v1.4.1](https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.4.1).

**Comment by arko-betersport** [comment]
Thank you. It works perfectly!
