### ISSUE TITLE
Error while npm install

### ISSUE THREAD

**Issue by siyahulhaq-ceymox** [scandipwa/create-magento-app#25]
I had tried to create an new magento backend with create-magento-app but unfortunately its throwing an error that docker.getContainers is not a function this is the new issue i am facing in latest version (1.2.3) i think its a bug please fix it soon.
![scandi res](https://user-images.githubusercontent.com/76936407/120306268-4ffec100-c2ef-11eb-9935-d70503948967.PNG)

**Comment by ejnshtein** [comment]
Yes indeed, this was fixed yesterday in version 1.5.2 https://github.com/scandipwa/create-magento-app/releases/tag/%40scandipwa%2Fmagento-scripts%401.5.2

**Comment by ejnshtein** [comment]
Closing since it's fixed in latest releases.
