### ISSUE TITLE
Support For Win32 (arch x64)

### ISSUE THREAD

**Issue by abrorAbdullaev** [scandipwa/create-magento-app#31]
Windows 10 Home OS users cannot use the package, on install attempt the following error is displayed:

```npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @scandipwa/magento-scripts@1.11.0: wanted {"os":"darwin,linux","arch":"x64,arm64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS: darwin,linux
npm ERR! notsup Valid Arch: x64,arm64
npm ERR! notsup Actual OS: win32
npm ERR! notsup Actual Arch: x64
```
Seems like the dependencies of the package is not so much platform sensitive, thus it would be possible maybe just to add the os win32 to the allowed os list.

**Comment by ejnshtein** [comment]
Well, you are trying to install our scripts on Windows, but it's supported only in WSL mode.
We have no plans on supporting plain Windows at the moment.
