### ISSUE TITLE
Error: No composer version found in composer version output

### ISSUE THREAD

**Issue by MarkNBroadhead** [scandipwa/create-magento-app#35]
### Is your proposal related to a problem?

When running the installer, I got the error "No composer version found in composer version output!"
After an hour of debugging, I was able to find that the cached composer.phar in the node_modules/.create-magento-app-cache/ dir had failed to download and had a size of 0 bytes. Finding this directory took some time digging through the code.

### Describe the solution you'd like

This took me a long time to fix. Options to make this easier for the end user:
* On error messages like this, print out the cache directory, prompting the user to check the file.
* On failure, try to re-download the file.

### Additional context

Thank you for this awesome tool!

**Comment by ejnshtein** [comment]
Hi!
Thanks for your report! This is a good idea!
Will add to todo and will try release in the next update!
