### ISSUE TITLE
When browser is launched 404 is shown

### ISSUE THREAD

**Issue by ejnshtein** [scandipwa/create-magento-app#39]
### Describe the bug

After the CMA app is installed and booted with the CSA theme in the browser on the home page of the website it says 404 error.

<img width="1038" alt="Page not found 2021-12-22 20-36-27" src="https://user-images.githubusercontent.com/18352350/147240322-6834d6f5-0d42-438b-9b71-e1a36ab345ff.png">

### Expected behavior

CMA should inject CMS home page into the database with instructions on how to install sample-data or import database dump.

**Comment by ejnshtein** [comment]
Looks like this problem is related to ScandiPWA itself, since on clean install on homepage Magento prints "Homepage goes here".

**Comment by TechDanil** [comment]
> Looks like this problem is related to ScandiPWA itself, since on clean install on homepage Magento prints "Homepage goes here". ![Screenshot_20211223_153043](https://user-images.githubusercontent.com/18352350/147247454-5d40be16-536d-4fc4-9b36-9bcb7fa57322.png)

Tell me how u solved it

**Comment by ejnshtein** [comment]
If you see that page, then you need to select scandipwa as your frontend theme in admin panel

**Comment by TechDanil** [comment]
> If you see that page, then you need to select scandipwa as your frontend theme in admin panel

Ive already done it in content -> configuration -> and chose my theme but i  still see it
