### ISSUE TITLE
Linux prerequisites for cma do not indicate cmake

### ISSUE THREAD

**Issue by carinadues** [scandipwa/create-magento-app#43]
**Description**:
Issue reported by @romeof1980 in https://github.com/scandipwa/scandipwa/issues/3857:
After taking care of the pre-requisites launching `yarn create magento-app my-app`

**Expected behavior**:
Receive the following message:
```
Done in 16.77s.
Success! Created Magento 2 application "my-app"
```

**Actual results**
Following error:
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory 'dkprojects/scandipwa5/scandi504/node_modules/cpu-features/build'
  ACTION Configuring dependencies dkprojects/scandipwa5/scandi504/node_modules/cpu-features/deps/cpu_features/build/Makefile
**/bin/sh: 1: cmake: not found**
make: *** [config_deps.target.mk:13: dkprojects/scandipwa5/scandi504/node_modules/cpu-features/deps/cpu_features/build/Makefile] Error 127
make: Leaving directory 'dkprojects/scandipwa5/scandi504/node_modules/cpu-features/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.11.0-41-generic
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd dkprojects/scandipwa5/scandi504/node_modules/cpu-features
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"

```

**How to solve**:
`sudo apt-get install cmake`

**How to avoid**:
Scandipwa docs should specify "cmake" in the Linux Prerequisites-Linux requirements-Ubuntu: 
https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-linux#1.-install-platform-specific-dependencies
must add:
`sudo apt-get -y install cmake
`

**Versions**:
- Installed "create-magento-app@1.2.4" with binaries:  - create-magento-app
- yarn install v1.22.15
- Ubuntu 20.04.3 LTS
- Processor: Intel® Core™ i5-9300H CPU @ 2.40GHz × 8

**Comment by ejnshtein** [comment]
Yes, so fix is released in [create-magento-app@1.2.5](https://github.com/scandipwa/create-magento-app/releases/tag/create-magento-app%401.2.5).
