### ISSUE TITLE
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing

### ISSUE THREAD

**Issue by Morgy93** [scandipwa/create-magento-app#58]
### Describe the bug

The `npx create-magento-app my-app` can fail because of outdated package updates on the host.
`E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing`

Since this project is aimed to handle everything automatically this should be caught as well.

### Which terms did you search for in User Guide?

(Write your answer here if relevant.)

### Environment

WSL2 Ubuntu

### Steps to reproduce

Well, somehow get outdated package updates and try to run `npx create-magento-app my-app`

### Expected behavior

Something like `sudo apt update` to be run automatically

### Actual behavior

Packages were not updated automatically, so the install failed and the user had to take manual actions to fix the error.

**Comment by ejnshtein** [comment]
Hi!

Thanks for the report again!

"Since this project is aimed to handle everything automatically this should be caught as well." - this is not an exactly correct description of this project. It aims to streamline Magento installation, not break your system. If you have outdated packages you should deal with them yourself.
We don't really want to be responsible if `sudo apt update` will break your system for some reason.

**Comment by Morgy93** [comment]
> "Since this project is aimed to handle everything automatically this should be caught as well." - this is not an exactly correct description of this project.

Alright, that was probably mistakable communicated by Alfreds Genkins on the MM22IN talk "Building self-correcting Magento local setup" where it was stated "it handles everything for you automatically" VERY enthusiastically 😅 

But fine for me, just wanted to report in terms of convenience for some sort of "do you want to update your packages before install?" instead of just failing installation. 

You may just close this ticket if not interested.

**Comment by Morgy93** [comment]
By the way, don't mistake `apt update` (== "safe") with `apt upgrade` (== "dangerous") because I only meant the `update` part alone.

**Comment by ejnshtein** [comment]
Oh I see, I see.

Well true, I think we can add a prompt to run update before installing packages.
Although, only Ubuntu requires that :smiley:
