### ISSUE TITLE
Bug when run command yarn start

### ISSUE THREAD

**Issue by dylanngo95** [scandipwa/create-magento-app#8]
## Run command in ubuntu 20.04
yarn start

![Screenshot from 2021-01-25 17-41-11](https://user-images.githubusercontent.com/11944757/105695578-d7e55080-5f34-11eb-8740-bbe309f40892.png)

Thanks.

**Comment by ejnshtein** [comment]
Hi!
Can you give details from command `tail -F /home/dylan/.phpbrew/build/php-7.4.13/build.log` or upload this file somewhere?
As for now, looks like you are missing some dependency in your system.

**Comment by ejnshtein** [comment]
Yeah, "no acceptable C compiler found in $PATH" means that you didn't install it. [stackoverflow](https://askubuntu.com/questions/237576/no-acceptable-c-compiler-found-in-path/237588)

Platform-specific dependency list for CMA can be obtained here: https://docs.create-magento-app.com/getting-started/prerequisites/installation-on-linux

**Comment by dylanngo95** [comment]
Thank @ejnshtein. It depends to C compiler

**Comment by rperozin** [comment]
I have the same problem.

I'm using a Mac, so I'm using homebrew and not apt-get, and `sudo apt-get install build-essential` don't solve my problem.
In other discussions at StackOverflow, they suggest running `xcode-select --install`, but I'm still having the same issue afterwards.

How can I solve this issue?

![image](https://user-images.githubusercontent.com/91266442/136396136-3cb3c7f1-f03e-49d3-9817-503fc9e3538c.png)

**Comment by rperozin** [comment]
@ejnshtein Yes, solved. Now the `npm run start` is installing the Magento 2.4.3.

Important to mention for other developers. This https://github.com/scandipwa/create-magento-app/issues/8#issuecomment-937935099 solution also solve the openssl error `make: *** [ext/openssl/openssl.lo] Error 1` that happen while Checking patch for php5.6 with openssl 1.1.x patch.
